-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS tourney (
    id integer primary key generated always as identity,
    name text NOT NULL,
    "draftHasStarted" boolean NOT NULL,
    "isDraftPaused" boolean NOT NULL,
    "allowClock" boolean NOT NULL,
    "currentDay" smallint,
    "worstScoresForDay" text,
    "startDateEpochMillis" bigint NOT NULL,
    "lastUpdatedEpochMillis" bigint NOT NULL,
    config text NOT NULL
);

ALTER TABLE tourney
  enable row level security;

CREATE INDEX IF NOT EXISTS "tourney_name_index" ON golfer("tourneyId");


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS golfer (
    id integer primary key generated always as identity,
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    name text NOT NULL,
    wgr smallint
);

ALTER TABLE golfer
  enable row level security;

-- Indices -------------------------------------------------------

CREATE INDEX IF NOT EXISTS "golfer_tourneyId_idx" ON golfer("tourneyId");


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS gd_user (
    id integer primary key generated always as identity,
    name text NOT NULL,
    username text NOT NULL
);

ALTER TABLE gd_user
  enable row level security;

-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS app_state (
    "activeTourneyId" integer NOT NULL REFERENCES tourney(id)
);

ALTER TABLE app_state
  enable row level security;


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS draft_auto_pick (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "userId" integer NOT NULL REFERENCES gd_user(id),
    "autoPick" boolean NOT NULL,
    PRIMARY KEY ("tourneyId", "userId", "autoPick")
);

ALTER TABLE draft_auto_pick
  enable row level security;



-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS draft_pick (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "pickNumber" integer NOT NULL,
    "userId" integer NOT NULL REFERENCES gd_user(id),
    "golferId" integer REFERENCES golfer(id),
    "timestampEpochMillis" bigint,
    "clientTimestampEpochMillis" bigint,
    PRIMARY KEY ("tourneyId", "pickNumber")
);
ALTER TABLE draft_pick
  enable row level security;


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS draft_pick_list (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "userId" integer NOT NULL REFERENCES gd_user(id),
    "golferIds" integer[] NOT NULL,
    PRIMARY KEY ("tourneyId", "userId")
);
ALTER TABLE draft_pick_list
  enable row level security;


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS golfer_score (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "golferId" integer NOT NULL REFERENCES golfer(id),
    day smallint NOT NULL,
    thru smallint,
    scores text NOT NULL,
    PRIMARY KEY ("tourneyId", "golferId", day)
);
ALTER TABLE golfer_score
  enable row level security;


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS tourney_standings (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "userId" integer NOT NULL REFERENCES gd_user(id),
    "totalScore" smallint NOT NULL,
    standing smallint NOT NULL,
    "isTied" boolean NOT NULL,
    PRIMARY KEY ("tourneyId", "userId")
);
ALTER TABLE tourney_standings
  enable row level security;


-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS tourney_standing_scores (
    "tourneyId" integer NOT NULL REFERENCES tourney(id),
    "userId" integer NOT NULL REFERENCES gd_user(id),
    day smallint NOT NULL,
    "totalScore" smallint NOT NULL,
    "golferScores" text NOT NULL,
    PRIMARY KEY ("tourneyId", "userId", day)
);
ALTER TABLE tourney_standing_scores
  enable row level security;
